spring:
  application:
    name: backend

  jackson:
    date-format: "yyyy-MM-dd HH:mm"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://localhost:5432/securitydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false